# Generated by Django 5.2.8 on 2025-11-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_problems_problem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['date_achieved']},
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['date_solved']},
        ),
    ]
